name: Checks

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  stylua:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Check formatting
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
